language: android

android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository

jdk: oraclejdk8

notifications:
  email: false

env:
    matrix:
        - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=2    #Time out to 2 mins

sudo: false

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle
